### ISSUE TITLE
Need help. Boot loop

### ISSUE THREAD

**Issue by shmrymbd** [hpsaturn/esp32-s3-clock#1]
Hi i am using WT32-SC01-PLUS  ( WT32-S3-WROVER-N16R2). Pls help me what is wrong with platformio.ini setting
This is finding

`esptool.py v4.3
Found 5 serial ports
Serial port /dev/cu.wlan-debug
/dev/cu.wlan-debug failed to connect: Could not open /dev/cu.wlan-debug, the port doesn't exist
Serial port /dev/cu.wchusbserial544C0091511
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: f4:12:fa:c0:94:ac
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4017
Detected flash size: 8MB
Hard resetting via RTS pin...`
```
ELF file SHA256: 0000000000000000

Rebooting...
␀�ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x40376e2c
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x43c
load:0x403b6000,len:0xbd0
load:0x403ba000,len:0x29c8
SHA-256 comparison failed:
Calculated: 27beaa143e4753b6cdeed5b388d3ebbf4c921ce01156fd10673139a323a25557
Expected: 6eb14ec480aff4f05e39378c41406102ac163573741e63b6cfd73509ef44e3bd
Attempting to boot anyway...
entry 0x403b61d8
E (274) spi_flash: Detected size(8192k) smaller than the size in the binary image header(16384k). Probe failed.

assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK)


Backtrace:0x40377202:0x3fceb1800x4037cf59:0x3fceb1a0 0x40382ca5:0x3fceb1c0 0x42034946:0x3fceb2f0 0x40376b8d:0x3fceb320 0x403bafc7:0x3fceb350 0x403bb24e:0x3fceb380 0x403b622d:0x3fceb4b0 0x40045c01:0x3fceb570  |<-CORRUPTED
```

**Comment by hpsaturn** [comment]
sorry for the delay. Please check the last version.
